### ISSUE TITLE
Cannot use EventStreams.eventsOf with MenuItem

### ISSUE THREAD

**Issue by Gurkenmaster** [TomasMikula/ReactFX#14]
MenuItem menuItem = ...;
     EventStream<ActionEvent> stream = EventStreams.eventsOf(menuItem, ActionEvent.ACTION);

Doesn't work because MenuItem doesn't extend Node.
This is just a minor inconvenience because I can simply adjust that method for MenuItem.

**Comment by TomasMikula** [comment]
You are right, thanks for reporting.

A while back I created [a ticket](https://javafx-jira.kenai.com/browse/RT-38642) asking for a common superinterface for objects that receive events. I included Node and Scene as examples, and now I added a comment about `MenuItem`.

In the meantime, I can add the method to `EventStreams`.
