### ISSUE TITLE
Combining multiple Vals

### ISSUE THREAD

**Issue by sinicyn** [TomasMikula/ReactFX#18]
Adding a way to combine instances of `Val`, like `EasyBind.combine(...)` would fully cover functionallity of EasyBind.

May be except `EasyBind.select(...)`, but I dont use it :)

**Comment by sinicyn** [comment]
Oh, there is `Val.combine(...)`!

**Comment by TomasMikula** [comment]
`EasyBind.select()` is covered as well, by `flatMap`:

```java
Val<Boolean> b = Val.flatMap(control.sceneProperty(), Scene::windowProperty)
        .flatMap(Window::showingProperty);
```

**Comment by sinicyn** [comment]
What about `EasyBind.includeWhen(...)`? I cant find an analog for Val or LiveList.

**Comment by TomasMikula** [comment]
This one does not have an equivalent yet. My thinking is that in ReactFX it should be done in a different way. `EasyBind.includeWhen(collection, element, condition)` immediately starts observing `condition`. The common theme in ReactFX is lazy binding, and preserving laziness on composition.

My current thinking is something like this:

```java
final T element = ...;
LiveList<T> maybeElem = condition.map(cond -> cond ? element : null).asList();
LiveList<T> list = LiveList.concat(originalList, maybeElem);
```

where the missing pieces are `Val.asList()`, which returns a _view_ of a `Val` as a `LiveList` of zero or one element, and `LiveList.concat(LiveList<T>...)`, which returns a concatenation view of multiple observable lists.

The resulting `list` in my example does binds _lazily_ to `originalList` and `maybeElem`, and `maybeElem` binds lazily to `condition`. Therefore, there is no observer of `condition` unless there is an observer of the resulting `list`.

This is a little bit more verbose than `includeWhen`, so some more convenient method might be added as well.
