### ISSUE TITLE
Make an EventStream active based on a SimpleObjectProperty's bean value

### ISSUE THREAD

**Issue by JordanMartinez** [TomasMikula/ReactFX#27]
How do I make an EventStream active only when an ObjectProperty's bean matches a specific value? (In this case, the ObjectProperty holds an Enum.) As of right now, a stream is always active unless suspended when an Observable<Boolean> is true. What's the best way to reverse this (an EventStream is active only when an ObjectProperty holds a specific value)?

````groovy
enum State {
    UNFINISHED,
    CONNECTED,
    ROOT
}
SimpleObjectProperty<State> state = new SimpleObjectProperty(State.UNFINISHED)
````
I want to create 3 EventStreams, each of which are only active when 'state' holds a specific value:
1. Stream A is only active when state's bean == State.UNFINISHED
2. Stream B is only active when state's bean == State.CONNECTED
3. Stream C is only active when state's bean == State.ROOT

**Comment by TomasMikula** [comment]
```java
EventStream<T> stream = ...;

EventStream<T> streamA = stream.suppressWhen(Bindings.notEqual(state, State.UNFINISHED));
EventStream<T> streamB = stream.suppressWhen(Bindings.notEqual(state, State.CONNECTED));
EventStream<T> streamC = stream.suppressWhen(Bindings.notEqual(state, State.ROOT));
```

**Comment by JordanMartinez** [comment]
Excellent! Thank you sir!
