### ISSUE TITLE
What is the graceful way to dispatch in the eventstream recursicely?

### ISSUE THREAD

**Issue by lyrachord** [TomasMikula/ReactFX#30]
For a normal EventSource, it cannot be recursively pushed events into. This way will lead to a illegal state exception because of the recursive operation.
So what is the graceful way for the recursive operations?
Thanks

**Comment by TomasMikula** [comment]
You need to tell the event stream what to do with an incoming event when not all listeners have been notified of the previous event yet. There are multiple ways to handle this, so event streams don't pick one for you. Use one of the `onRecurse*` methods to specify what you want to do. For example, use [`onRecurseQueue()`](http://www.reactfx.org/javadoc/2.0-M4u1/org/reactfx/EventStream.html#onRecurseQueue--) to just enqueue the events and emit them one by one (each of the emissions could produce new events, that would be added to the queue). Use [`onRecurseRetainLatest()`](http://www.reactfx.org/javadoc/2.0-M4u1/org/reactfx/EventStream.html#onRecurseRetainLatest--) if in case of recursive events, you are interested only in the most recent one. There are `onRecurseReduce` and `onRecurseAccumulate` that are more general and can be used to implement other behavior (queue and retainLatest are in fact implemented using these more general methods).

Note that for `Val` and `LiveList`, there is one natural thing to do on recursive changes, so they support recursive changes out of the box and don't need you to decide what to do. That thing is, two subsequent changes can always be combined into one. For `Val`, if there is a change from `x` to `y` and then a change from `y` to `z`, this will be combined into a single change from `x` directly to `z`. For lists it is more complicated, but still well defined and doable.

**Comment by lyrachord** [comment]
I just employ the onRecurseQueue method on a EventSource, it works fine for my case(some input event completed, a new event push back immediately).

Many thanks.
