### ISSUE TITLE
compiler warning on util.Lists in eclipse compiler

### ISSUE THREAD

**Issue by lyrachord** [TomasMikula/ReactFX#31]
Hi Mikula,
There is a compiler warning in eclipse at util/Lists.java because of jdt.
a type cast added. 
Is this OK?

```
diff --git a/reactfx/src/main/java/org/reactfx/util/Lists.java b/reactfx/src/main/java/org/reactfx/util/Lists.java
index 2140a23..5761204 100644
--- a/reactfx/src/main/java/org/reactfx/util/Lists.java
+++ b/reactfx/src/main/java/org/reactfx/util/Lists.java
@@ -299,7 +299,7 @@ class ListConcatenation<E> extends AbstractList<E> {
     static <E> List<E> create(List<List<? extends E>> lists) {
         return lists.stream()
             .filter(l -> !l.isEmpty())
-            .map(l -> {
+            .<FingerTree>map(l -> {
                 @SuppressWarnings("unchecked") // cast safe because l is unmodifiable
                 List<E> lst = (List<E>) l;
                 return lst instanceof ListConcatenation
```

**Comment by TomasMikula** [comment]
Hi, I don't get any warnings in eclipse for the original code. My jdt version is
`Eclipse Java Development Tools 3.10.1.v20150204-1700`, with Eclipse 4.3.0. Is your version older or newer?

If I add the `<FingerTree>` type annotation as you suggest, then I get a warning

    FingerTree is a raw type. References to generic type FingerTree<T,S> should be parameterized

**Comment by lyrachord** [comment]
Ah, a bit strange, my jdt is 4.5 now, and 4.4 is used early.
There is a the warning in both.

**Comment by TomasMikula** [comment]
That is Eclipse version, not jdt version, right. Also, I was wrong about my eclipse version, it is 4.4, not 4.3.

**Comment by lyrachord** [comment]
Ah you're right, my stream forgetful:) 
seems jdt still growing?
