### ISSUE TITLE
org.reactfx.Change class lacks equals & hashCode methods

### ISSUE THREAD

**Issue by echebbi** [TomasMikula/ReactFX#68]
Hi,

I encountered an issue while using [UndoFX](https://github.com/TomasMikula/UndoFX), which makes use of ReactFX.

I created an `EventStream` of `Change` instances, thanks to `EventStreams.changesOf` method, that I gave to UndoFX. However, the library is unable to process it correctly because `Change` does not override `equals`.

I managed to overcome this limitation by using the `map` method to turn the `Stream <Change>` into a `Stream <ComparableChange>` (where `ComparableChange` is a new class I created).

It would be far easier if `Change` redefined directly `equals` and `hashCode`. What I propose is to consider two `Change` instances equal if both their old values and new values are equal.

If you agree I can submit a PR to fix the problem.

**Comment by JordanMartinez** [comment]
@KazeJiyu I think you are greatly misunderstanding something. The `change` object is a generic, so you are the one who creates the change object. If it lacks an implementation for the `equals` and `hashCode` methods, that's on you. In other words, you shouldn't be using `EventStreams.changesOf`. That's useful in other cases, but isn't meant to do what you are trying to do.

For an example of what is meant by `change` object, see RichTextFX, and in particular, these files:
- [ReadOnlyStyledDocument's replace method (which creates a new rich change)](https://github.com/FXMisc/RichTextFX/blob/eb0e2f189d3bb493e190ff147e2a5715020d481f/richtextfx/src/main/java/org/fxmisc/richtext/model/ReadOnlyStyledDocument.java#L279)
- [The RichTextChange class itself. This is what you need to create](https://github.com/FXMisc/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/model/RichTextChange.java)
- [The EditableStyledDocument update method](https://github.com/FXMisc/RichTextFX/blob/eb0e2f189d3bb493e190ff147e2a5715020d481f/richtextfx/src/main/java/org/fxmisc/richtext/model/GenericEditableStyledDocumentBase.java#L213-L222), which pushes the change to its event stream. That class as a whole should be looked over.

This may require you to change your model's data structure if you want to use UndoFX.

**Comment by echebbi** [comment]
I'm a _bit_ late but thanks for the clarification! I'm not using the library anymore so I'm closing the issue.
