### ISSUE TITLE
Question about how to combine streams

### ISSUE THREAD

**Issue by ubertakter** [TomasMikula/ReactFX#69]
I've read all the documentation I can find and have experimented quite a bit, but I just can't figure out what's going on. I posted my question on [StackOverflow](https://stackoverflow.com/questions/47803831/combining-multiple-change-streams-in-reactfx) and I'm posting here with the hope of getting my issue some attention. If my problem can be solved I think it would make a good use example to go in the wiki.

**Comment by JordanMartinez** [comment]
Looks like Tomas responded to your comment on his original post.

**Comment by ubertakter** [comment]
Yeah, I meant to close this. Thanks.
