### ISSUE TITLE
Converting a Var into a Val?

### ISSUE THREAD

**Issue by hjohn** [TomasMikula/ReactFX#74]
I have a Var used internally, and want to expose its value (read only) as a Val.

It seems that this should be pretty trivial, but there is no method on Var to accomplish this directly:

     Var<Integer> var = Var.newSimpleVar(0);
     Val<Integer> val = var.asVal();
     // or:
     Val<Integer> val = var.readOnly();

So for now I'm using:

     Val<Integer> val = var.orElseConst(0);

Am I missing something obvious?

**Comment by TomasMikula** [comment]
A `Var` already is a `Val`:

```java
public interface Var<T> extends Val<T>
```

**Comment by hjohn** [comment]
I was looking for functionality similar to what `ReadOnlyXXXWrapper`'s offers in JavaFX, something that cannot be casted back to a writable value.  However, I think it will be good enough for now, I just like to program defensively.

**Comment by TomasMikula** [comment]
I would say that if a user is using casts/reflection, they are shooting themselves in the foot and there's nothing we can do to help them.

If you really want not-a-`Var`, you could do `Val<Integer> val = var.map(i -> i)`.

**Comment by hjohn** [comment]
Thanks, closing this.
